name: update awesome-stars
on:
  schedule:
  - cron: 0 10 * * *
  push:
    branches: [ master ]
jobs:
  awesome-stars:
    name: update awesome-stars
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install starred
    - name: update repo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: starred --username dotiful --repository starred --sort --token ${GITHUB_TOKEN} --message 'update stars'
